<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.5 on win32)" generated="20240124 16:14:49.808" rpa="false" schemaversion="3">
<suite id="s1" name="Automation Mobile" source="C:\Automation_Mobile">
<suite id="s1-s1" name="Mobile" source="C:\Automation_Mobile\mobile">
<suite id="s1-s1-s1" name="Tests" source="C:\Automation_Mobile\mobile\tests">
<suite id="s1-s1-s1-s1" name="Login" source="C:\Automation_Mobile\mobile\tests\login.robot">
<test id="s1-s1-s1-s1-t1" name="Deve logar com sucesso" line="13">
<kw name="Start App" library="base" type="SETUP">
<kw name="Open Application">
<arg>http://localhost:4723/wd/hub</arg>
<arg>alias=Smartbit</arg>
<arg>automationName=UiAutomator2</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Android Simulator</arg>
<arg>app=${EXECDIR}/app/smartbit-beta.apk</arg>
<arg>udid=emulator-5554</arg>
<arg>autoGrantPermissions=true</arg>
<msg timestamp="20240124 16:14:50.561" level="FAIL">No keyword with name 'Open Application' found.</msg>
<status status="FAIL" starttime="20240124 16:14:50.556" endtime="20240124 16:14:50.564"/>
</kw>
<kw name="Wait Until Page Contains">
<arg>Informe seu c√≥digo de acesso</arg>
<status status="NOT RUN" starttime="20240124 16:14:50.573" endtime="20240124 16:14:50.576"/>
</kw>
<status status="FAIL" starttime="20240124 16:14:50.548" endtime="20240124 16:14:50.588"/>
</kw>
<kw name="Finish App" library="base" type="TEARDOWN">
<kw name="Capture Page Screenshot">
<msg timestamp="20240124 16:14:50.605" level="FAIL">No keyword with name 'Capture Page Screenshot' found.</msg>
<status status="FAIL" starttime="20240124 16:14:50.597" endtime="20240124 16:14:50.610"/>
</kw>
<kw name="Close Application">
<msg timestamp="20240124 16:14:50.627" level="FAIL">No keyword with name 'Close Application' found.</msg>
<status status="FAIL" starttime="20240124 16:14:50.619" endtime="20240124 16:14:50.631"/>
</kw>
<status status="FAIL" starttime="20240124 16:14:50.590" endtime="20240124 16:14:50.637">Several failures occurred:

1) No keyword with name 'Capture Page Screenshot' found.

2) No keyword with name 'Close Application' found.</status>
</kw>
<status status="FAIL" starttime="20240124 16:14:50.542" endtime="20240124 16:14:50.659">Setup failed:
No keyword with name 'Open Application' found.

Also teardown failed:
Several failures occurred:

1) No keyword with name 'Capture Page Screenshot' found.

2) No keyword with name 'Close Application' found.</status>
</test>
<doc>Suite de testes de login</doc>
<status status="FAIL" starttime="20240124 16:14:49.917" endtime="20240124 16:14:50.670"/>
</suite>
<status status="FAIL" starttime="20240124 16:14:49.910" endtime="20240124 16:14:50.731"/>
</suite>
<status status="FAIL" starttime="20240124 16:14:49.901" endtime="20240124 16:14:50.748"/>
</suite>
<status status="FAIL" starttime="20240124 16:14:49.822" endtime="20240124 16:14:50.756"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Automation Mobile">Automation Mobile</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Mobile">Automation Mobile.Mobile</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="Tests">Automation Mobile.Mobile.Tests</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1-s1" name="Login">Automation Mobile.Mobile.Tests.Login</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240124 16:14:49.940" level="ERROR">Error in file 'C:\Automation_Mobile\mobile\resources\base.resource' on line 4: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Automation_Mobile\lib
  C:\Automation_Mobile\resources
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\verus\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\verus\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20240124 16:14:49.955" level="ERROR">Error in file 'C:\Automation_Mobile\mobile\resources\base.resource' on line 5: Importing library 'JSONLibrary' failed: ModuleNotFoundError: No module named 'JSONLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Automation_Mobile\lib
  C:\Automation_Mobile\resources
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\verus\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\verus\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20240124 16:14:49.976" level="ERROR">Error in file 'C:\Automation_Mobile\mobile\resources\screens\login.resource' on line 4: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Automation_Mobile\lib
  C:\Automation_Mobile\resources
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\verus\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\verus\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20240124 16:14:50.015" level="ERROR">Error in file 'C:\Automation_Mobile\mobile\resources\screens\help.resource' on line 4: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Automation_Mobile\lib
  C:\Automation_Mobile\resources
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\verus\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\verus\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20240124 16:14:50.046" level="ERROR">Error in file 'C:\Automation_Mobile\mobile\resources\screens\components\popup.resource' on line 4: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Automation_Mobile\lib
  C:\Automation_Mobile\resources
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\verus\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\verus\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20240124 16:14:50.096" level="ERROR">Error in file 'C:\Automation_Mobile\mobile\resources\screens\components\footer.resource' on line 4: Importing library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'AppiumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Automation_Mobile\lib
  C:\Automation_Mobile\resources
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\verus\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\verus\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20240124 16:14:50.514" level="ERROR">Error in file 'C:\Automation_Mobile\mobile\resources\database.resource' on line 4: Importing library 'DatabaseLibrary' failed: ModuleNotFoundError: No module named 'DatabaseLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Automation_Mobile\lib
  C:\Automation_Mobile\resources
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\libs
  c:\Users\verus\.vscode\extensions\d-biehl.robotcode-0.69.0\bundled\tool\robotcode
  C:\Users\verus\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\verus\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\verus\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
</errors>
</robot>
